// <auto-generated />
using DatabaseModel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MusicChart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180302125007_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuisnessModel.Models.SimiliarMap", b =>
                {
                    b.Property<string>("SimiliarMapId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("SimiliarSingerId");

                    b.Property<string>("SingerId");

                    b.HasKey("SimiliarMapId");

                    b.ToTable("SimiliarMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
